services:
  filesystem-server:
    build:
      context: ./servers/filesystem
    ports:
      - 8081:8000
  memory-server:
    build:
      context: ./servers/memory
    ports:
      - 8082:8000
    volumes:
      - memory:/app/data:rw
  time-server:
    build:
      context: ./servers/time
    ports:
      - 8083:8000

  s3:
    build:
      context: ./servers/s3
    environment:
      - AWS_ENDPOINT_URL:
      - AWS_ACCESS_KEY_ID:
      - AWS_SECRET_ACCESS_KEY:
    ports:
      - 8084:8000

volumes:
  memory:
